class ListSign {
  static ListMandatory = {
    tsr1: [
      {
        name: 'درخواست کننده',
        firstName: 'author_firstName',
        lastName: 'author_lastName',
        notShowDefault: true,
        not_have_check: true
      },
      {
        name: 'رئیس واحد',
        value: 'unit_boss',
        select: 'unit_boss_select',
        itemReject: [
          { name: 'رد', value: 'reject' },
          { name: 'اصلاحیه', value: 'comment' }
        ],
        permission: 'unit_boss_verify_allow',
        state: 'unit_boss_verify',
        message: 'unit_boss_verify_msg',
        url: 'tsr1Sign/unit_boss',
        firstName: 'unit_boss_verify_firstName',
        lastName: 'unit_boss_verify_lastName'
        // hold: 'verified'
      },
      {
        name: 'رئیس اداره/امور',
        value: 'office_boss',
        select: 'office_boss_select',
        itemReject: [
          { name: 'رد', value: 'reject' },
          { name: 'اصلاحیه', value: 'comment' }
        ],
        permission: 'office_boss_verify_allow',
        state: 'office_boss_verify',
        message: 'office_boss_verify_msg',
        url: 'tsr1Sign/office_boss',
        hold: 'unit_boss_verify',
        firstName: 'office_boss_verify_firstName',
        lastName: 'office_boss_verify_lastName'
      },
      {
        name: 'مدیر خدمات فنی',
        value: 'verified',
        select: 'select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        // permission: 'verified_allow',
        state: 'verified',
        message: 'verify_msg',
        url: 'tsr4Sign/author',
        // filter2: 'value',
        // filter: 'author',
        // system: true,
        firstName: 'verified_firstName',
        lastName: 'verified_lastName',
        notShowDefault: true,
        cantReject: true
      }
    ],
    tsr2: [
      {
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName',
        name: 'مهندسی عمومی'
      },
      {
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName',
        name: 'مهندسی فرآیند'
      },
      {
        firstName: 'inspection_boss_verify_firstName',
        lastName: 'inspection_boss_verify_lastName',
        name: 'بازرسی فنی'
      }
    ],
    tsr2_1: [
      {
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName',
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss',
        select: 'general_boss_select',
        permission: 'general_boss_verify_allow',
        state: 'general_boss_verify',
        message: 'general_boss_verify_msg',
        url: 'tsr2Sign/general_boss',
        cantReject: true
      }
    ],
    tsr2_2: [
      {
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName',
        name: 'رئیس مهندسی فرآیند',
        value: 'process_boss',
        select: 'process_boss_select',
        permission: 'process_boss_verify_allow',
        state: 'process_boss_verify',
        message: 'process_boss_verify_msg',
        url: 'tsr2Sign/process_boss',
        cantReject: true
      }
    ],
    tsr2_3: [
      {
        firstName: 'inspection_boss_verify_firstName',
        lastName: 'inspection_boss_verify_lastName',
        name: 'رئیس بازرسی فنی',
        value: 'inspection_boss',
        select: 'inspection_boss_select',
        permission: 'inspection_boss_verify_allow',
        state: 'inspection_boss_verify',
        message: 'inspection_boss_verify_msg',
        url: 'tsr2Sign/inspection_boss',
        cantReject: true
      }
    ],
    tsr3: [
      {
        name: 'بررسی کننده',
        value: 'author',
        select: 'author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'author_verify_allow',
        state: 'author_verify',
        message: 'author_verify_msg',
        url: 'tsr3Sign/author',
        // filter2: 'value',
        // filter: 'author',
        // system: true,
        firstName: 'author_verify_firstName',
        lastName: 'author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'supervisor',
        select: 'supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'supervisor_verify_allow',
        state: 'supervisor_verify',
        message: 'supervisor_verify_msg',
        url: 'tsr3Sign/supervisor',
        filter: 'مهندسی فرآیند و کنترل تولید',
        filter2: 'user_unit',
        firstName: 'supervisor_verify_firstName',
        lastName: 'supervisor_verify_lastName',
        hold: 'author_verify'
      },
      {
        name: 'بهینه سازی و مدیریت انرژی، کربن و آب',
        value: 'energy_manager',
        select: 'energy_manager_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'energy_manager_verify_allow',
        state: 'energy_manager_verify',
        message: 'energy_manager_verify_msg',
        url: 'tsr3Sign/energy_manager',
        firstName: 'energy_manager_verify_firstName',
        lastName: 'energy_manager_verify_lastName',
        filter2: 'value',
        filter: 'energy_manager',
        hold: 'supervisor_verify',
        system: true
      },
      {
        name: 'رئیس مهندسی فرآیند',
        value: 'process_boss',
        select: 'process_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'process_boss_verify_allow',
        state: 'process_boss_verify',
        message: 'process_boss_verify_msg',
        url: 'tsr3Sign/process_boss',
        hold: 'supervisor_verify',
        filter2: 'value',
        filter: 'process_boss',
        system: true,
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName',
        not_dispatch: true
      }
    ],
    tsr4: [
      {
        name: 'بررسی کننده',
        value: 'author',
        select: 'author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'author_verify_allow',
        state: 'author_verify',
        message: 'author_verify_msg',
        url: 'tsr4Sign/author',
        // filter2: 'value',
        // filter: 'author',
        // system: true,
        firstName: 'author_verify_firstName',
        lastName: 'author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس ایمنی و آتش نشانی',
        value: 'fire_boss',
        select: 'fire_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fire_boss_verify_allow',
        state: 'fire_boss_verify',
        message: 'fire_boss_verify_msg',
        url: 'tsr4Sign/fire_boss',
        filter2: 'value',
        filter: 'fire_boss',
        system: true,
        firstName: 'fire_boss_verify_firstName',
        lastName: 'fire_boss_verify_lastName',
        hold: 'author_verify'
      },
      {
        name: 'کارشناس HSE',
        value: 'hse_technician',
        select: 'hse_technician_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'hse_technician_verify_allow',
        state: 'hse_technician_verify',
        message: 'hse_technician_verify_msg',
        url: 'tsr4Sign/hse_technician',
        filter2: 'user_unit',
        filter: 'HSE_SD_ایمنی و آتش نشانی_SD_محیط زیست',
        firstName: 'hse_technician_verify_firstName',
        lastName: 'hse_technician_verify_lastName',
        hold: 'fire_boss_verify'
      },
      {
        name: 'رئیس امور HSE',
        value: 'hse_boss',
        select: 'hse_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'hse_boss_verify_allow',
        state: 'hse_boss_verify',
        message: 'hse_boss_verify_msg',
        url: 'tsr4Sign/hse_boss',
        filter2: 'value',
        filter: 'hse_boss',
        system: true,
        firstName: 'hse_boss_verify_firstName',
        lastName: 'hse_boss_verify_lastName',
        hold: 'hse_technician_verify',
        not_dispatch: true
      }
    ],
    tsr5: [
      {
        name: 'بررسی کننده',
        value: 'author',
        select: 'author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'author_verify_allow',
        state: 'author_verify',
        message: 'author_verify_msg',
        url: 'tsr5Sign/author',
        // filter2: 'value',
        // filter: 'author',
        // system: true,
        firstName: 'author_verify_firstName',
        lastName: 'author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'supervisor',
        select: 'supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'supervisor_verify_allow',
        state: 'supervisor_verify',
        message: 'supervisor_verify_msg',
        url: 'tsr5Sign/supervisor',
        filter: 'مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'supervisor_verify_firstName',
        lastName: 'supervisor_verify_lastName',
        hold: 'author_verify'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss',
        select: 'general_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_verify_allow',
        state: 'general_boss_verify',
        message: 'general_boss_verify_msg',
        url: 'tsr5Sign/general_boss',
        hold: 'supervisor_verify',
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        not_dispatch: true
      }
    ],
    tsr6: [
      {
        name: 'رئیس مهندسی فرآیند',
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName'
      },
      {
        name: 'رئیس مهندسی عمومی',
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName'
      },
      {
        name: 'رئیس بازرسی فنی',
        firstName: 'inspection_boss_verify_firstName',
        lastName: 'inspection_boss_verify_lastName'
      },
      {
        name: 'رئیس خدمات فنی',
        firstName: 'technical_boss_verify_firstName',
        lastName: 'technical_boss_verify_lastName'
      }
    ],

    tsr6_1: [
      {
        name: 'رئیس مهندسی فرآیند',
        value: 'process_boss',
        select: 'process_boss_select',
        // itemReject: [
        // ],
        permission: 'process_boss_verify_allow',
        state: 'process_boss_verify',
        message: 'process_boss_verify_msg',
        url: 'tsr6Sign/process_boss',
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName',
        cantReject: true
      }
    ],
    tsr6_2: [
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss',
        select: 'general_boss_select',
        // itemReject: [
        // { name: 'اصلاحیه', value: 'comment' },
        // { name: 'اصلاحیه قبل', value: 'edit_last_step' }
        // ],
        permission: 'general_boss_verify_allow',
        state: 'general_boss_verify',
        message: 'general_boss_verify_msg',
        url: 'tsr6Sign/general_boss',
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName',
        cantReject: true
      }
    ],
    tsr6_3: [
      {
        name: 'رئیس بازرسی فنی',
        value: 'inspection_boss',
        select: 'inspection_boss_select',
        // itemReject: [
        // ],
        permission: 'inspection_boss_verify_allow',
        state: 'inspection_boss_verify',
        message: 'inspection_boss_verify_msg',
        url: 'tsr6Sign/inspection_boss',
        firstName: 'inspection_boss_verify_firstName',
        lastName: 'inspection_boss_verify_lastName',
        cantReject: true
      }
    ],
    tsr6_4: [
      {
        name: 'رئیس خدمات فنی',
        value: 'technical_boss',
        select: 'technical_boss_select',
        // itemReject: [
        //   { name: 'اصلاحیه', value: 'comment' },
        //   { name: 'اصلاحیه قبل', value: 'edit_last_step' }
        // ],
        permission: 'technical_boss_verify_allow',
        state: 'technical_boss_verify',
        message: 'technical_boss_verify_msg',
        url: 'tsr6Sign/technical_boss',
        firstName: 'technical_boss_verify_firstName',
        lastName: 'technical_boss_verify_lastName',
        cantReject: true
      }
    ],
    tsr7_1: [
      {
        name: 'بررسی کننده',
        value: 'mechanical_author',
        select: 'mechanical_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'mechanical_author_verify_allow',
        state: 'mechanical_author_verify',
        message: 'mechanical_author_verify_msg',
        url: 'tsr7Sign/mechanical_author',
        firstName: 'mechanical_author_verify_firstName',
        lastName: 'mechanical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'mechanical_supervisor',
        select: 'mechanical_supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'mechanical_supervisor_verify_allow',
        state: 'mechanical_supervisor_verify',
        message: 'mechanical_supervisor_verify_msg',
        url: 'tsr7Sign/mechanical_supervisor',
        filter: 'مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'mechanical_supervisor_firstName',
        lastName: 'mechanical_supervisor_lastName',
        hold: 'mechanical_author_verify'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss_mechanical',
        select: 'general_boss_mechanical_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_mechanical_verify_allow',
        state: 'general_boss_mechanical_verify',
        message: 'general_boss_mechanical_verify_msg',
        url: 'tsr7Sign/general_boss_mechanical',
        hold: 'mechanical_supervisor_verify',
        firstName: 'general_boss_mechanical_verify_firstName',
        lastName: 'general_boss_mechanical_verify_lastName',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        not_dispatch: true
      },
      {
        name: 'رئیس خدمات فنی',
        value: 'technical_boss_mechanical',
        select: 'technical_boss_mechanical_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'technical_boss_mechanical_verify_allow',
        state: 'technical_boss_mechanical_verify',
        message: 'technical_boss_mechanical_verify_msg',
        url: 'tsr7Sign/technical_boss_mechanical',
        hold: 'general_boss_mechanical_verify',
        firstName: 'technical_boss_mechanical_verify_firstName',
        lastName: 'technical_boss_mechanical_verify_lastName',
        filter: 'technical_boss',
        filter2: 'value',
        system: true
      }
    ],
    tsr7_2: [
      {
        name: 'بررسی کننده',
        value: 'electrical_author',
        select: 'electrical_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_author_verify_allow',
        state: 'electrical_author_verify',
        message: 'electrical_author_verify_msg',
        url: 'tsr7Sign/electrical_author',
        firstName: 'electrical_author_verify_firstName',
        lastName: 'electrical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'electrical_supervisor',
        select: 'electrical_supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_supervisor_verify_allow',
        state: 'electrical_supervisor_verify',
        message: 'electrical_supervisor_verify_msg',
        url: 'tsr7Sign/electrical_supervisor',
        filter: 'مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'electrical_supervisor_firstName',
        lastName: 'electrical_supervisor_lastName',
        hold: 'electrical_author_verify'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss_electrical',
        select: 'general_boss_electrical_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_electrical_verify_allow',
        state: 'general_boss_electrical_verify',
        message: 'general_boss_electrical_verify_msg',
        url: 'tsr7Sign/general_boss_electrical',
        hold: 'electrical_supervisor_verify',
        firstName: 'general_boss_electrical_verify_firstName',
        lastName: 'general_boss_electrical_verify_lastName',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        not_dispatch: true
      },
      {
        name: 'رئیس خدمات فنی',
        value: 'technical_boss_electrical',
        select: 'technical_boss_electrical_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'technical_boss_electrical_verify_allow',
        state: 'technical_boss_electrical_verify',
        message: 'technical_boss_electrical_verify_msg',
        url: 'tsr7Sign/technical_boss_electrical',
        hold: 'general_boss_electrical_verify',
        firstName: 'technical_boss_electrical_verify_firstName',
        lastName: 'technical_boss_electrical_verify_lastName',
        filter: 'technical_boss',
        filter2: 'value',
        system: true
      }
    ],
    tsr7_3: [
      {
        name: 'بررسی کننده',
        value: 'instrument_author',
        select: 'instrument_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'instrument_author_verify_allow',
        state: 'instrument_author_verify',
        message: 'instrument_author_verify_msg',
        url: 'tsr7Sign/instrument_author',
        firstName: 'instrument_author_verify_firstName',
        lastName: 'instrument_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'instrument_supervisor',
        select: 'instrument_supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'instrument_supervisor_verify_allow',
        state: 'instrument_supervisor_verify',
        message: 'instrument_supervisor_verify_msg',
        url: 'tsr7Sign/instrument_supervisor',
        filter: 'مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'instrument_supervisor_firstName',
        lastName: 'instrument_supervisor_lastName',
        hold: 'instrument_author_verify'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss_instrument',
        select: 'general_boss_instrument_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_instrument_verify_allow',
        state: 'general_boss_instrument_verify',
        message: 'general_boss_instrument_verify_msg',
        url: 'tsr7Sign/general_boss_instrument',
        hold: 'instrument_supervisor_verify',
        firstName: 'general_boss_instrument_verify_firstName',
        lastName: 'general_boss_instrument_verify_lastName',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        not_dispatch: true
      },
      {
        name: 'رئیس خدمات فنی',
        value: 'technical_boss_instrument',
        select: 'technical_boss_instrument_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'technical_boss_instrument_verify_allow',
        state: 'technical_boss_instrument_verify',
        message: 'technical_boss_instrument_verify_msg',
        url: 'tsr7Sign/technical_boss_instrument',
        hold: 'general_boss_instrument_verify',
        firstName: 'technical_boss_instrument_verify_firstName',
        lastName: 'technical_boss_instrument_verify_lastName',
        filter: 'technical_boss',
        filter2: 'value',
        system: true
      }
    ],
    tsr7_4: [
      {
        name: 'بررسی کننده',
        value: 'building_author',
        select: 'building_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'building_author_verify_allow',
        state: 'building_author_verify',
        message: 'building_author_verify_msg',
        url: 'tsr7Sign/building_author',
        firstName: 'building_author_verify_firstName',
        lastName: 'building_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست',
        value: 'building_supervisor',
        select: 'building_supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'building_supervisor_verify_allow',
        state: 'building_supervisor_verify',
        message: 'building_supervisor_verify_msg',
        url: 'tsr7Sign/building_supervisor',
        filter: 'مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'building_supervisor_firstName',
        lastName: 'building_supervisor_lastName',
        hold: 'building_author_verify'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss_building',
        select: 'general_boss_building_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_building_verify_allow',
        state: 'general_boss_building_verify',
        message: 'general_boss_building_verify_msg',
        url: 'tsr7Sign/general_boss_building',
        hold: 'building_supervisor_verify',
        firstName: 'general_boss_building_verify_firstName',
        lastName: 'general_boss_building_verify_lastName',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        not_dispatch: true
      },
      {
        name: 'رئیس خدمات فنی',
        value: 'technical_boss_building',
        select: 'technical_boss_building_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'technical_boss_building_verify_allow',
        state: 'technical_boss_building_verify',
        message: 'technical_boss_building_verify_msg',
        url: 'tsr7Sign/technical_boss_building',
        hold: 'general_boss_building_verify',
        firstName: 'technical_boss_building_verify_firstName',
        lastName: 'technical_boss_building_verify_lastName',
        filter: 'technical_boss',
        filter2: 'value',
        system: true
      }
    ],
    tsr8_1: [
      {
        name: 'کارشناس',
        value: 'electrical_author',
        select: 'electrical_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_author_verify_allow',
        state: 'electrical_author_verify',
        message: 'electrical_author_verify_msg',
        url: 'tsr8Sign/electrical_author',
        firstName: 'electrical_author_verify_firstName',
        lastName: 'electrical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست گروه',
        value: 'electrical_supervisor_verify',
        select: 'electrical_supervisor_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_supervisor_verify_allow',
        state: 'electrical_supervisor_verify',
        message: 'electrical_supervisor_verify_msg',
        url: 'tsr8Sign/electrical_supervisor',
        filter: 'بازرسی فنی',
        filter2: 'user_unit',
        firstName: 'electrical_supervisor_firstName',
        lastName: 'electrical_supervisor_lastName',
        hold: 'electrical_author_verify'
      },
      {
        name: 'رئیس اداره بازرسی',
        value: 'electrical_inspection_boss_verify',
        select: 'electrical_inspection_boss_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_inspection_boss_verify_allow',
        state: 'electrical_inspection_boss_verify',
        message: 'electrical_inspection_boss_verify_msg',
        url: 'tsr8Sign/electrical_inspection_boss',
        filter: 'inspection_boss',
        filter2: 'value',
        system: true,
        firstName: 'electrical_inspection_boss_verify_firstName',
        lastName: 'electrical_inspection_boss_verify_lastName',
        hold: 'electrical_supervisor_verify',
        not_dispatch: true
      }
    ],
    tsr8_2: [
      {
        name: 'کارشناس',
        value: 'mechanical_author',
        select: 'mechanical_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'mechanical_author_verify_allow',
        state: 'mechanical_author_verify',
        message: 'mechanical_author_verify_msg',
        url: 'tsr8Sign/mechanical_author',
        firstName: 'mechanical_author_verify_firstName',
        lastName: 'mechanical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست گروه',
        value: 'mechanical_supervisor_verify',
        select: 'mechanical_supervisor_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'mechanical_supervisor_verify_allow',
        state: 'mechanical_supervisor_verify',
        message: 'mechanical_supervisor_verify_msg',
        url: 'tsr8Sign/mechanical_supervisor',
        filter: 'بازرسی فنی',
        filter2: 'user_unit',
        firstName: 'mechanical_supervisor_firstName',
        lastName: 'mechanical_supervisor_lastName',
        hold: 'mechanical_author_verify'
      },
      {
        name: 'رئیس اداره بازرسی',
        value: 'mechanical_inspection_boss_verify',
        select: 'mechanical_inspection_boss_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'mechanical_inspection_boss_verify_allow',
        state: 'mechanical_inspection_boss_verify',
        message: 'mechanical_inspection_boss_verify_msg',
        url: 'tsr8Sign/mechanical_inspection_boss',
        filter: 'inspection_boss',
        filter2: 'value',
        system: true,
        firstName: 'mechanical_inspection_boss_verify_firstName',
        lastName: 'mechanical_inspection_boss_verify_lastName',
        hold: 'mechanical_supervisor_verify',
        not_dispatch: true
      }
    ],
    tsr8_3: [
      {
        name: 'کارشناس',
        value: 'protection_author',
        select: 'protection_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'protection_author_verify_allow',
        state: 'protection_author_verify',
        message: 'protection_author_verify_msg',
        url: 'tsr8Sign/protection_author',
        firstName: 'protection_author_verify_firstName',
        lastName: 'protection_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست گروه',
        value: 'protection_supervisor_verify',
        select: 'protection_supervisor_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'protection_supervisor_verify_allow',
        state: 'protection_supervisor_verify',
        message: 'protection_supervisor_verify_msg',
        url: 'tsr8Sign/protection_supervisor',
        filter: 'بازرسی فنی',
        filter2: 'user_unit',
        firstName: 'protection_supervisor_firstName',
        lastName: 'protection_supervisor_lastName',
        hold: 'protection_author_verify'
      },
      {
        name: 'رئیس اداره بازرسی',
        value: 'protection_inspection_boss_verify',
        select: 'protection_inspection_boss_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'protection_inspection_boss_verify_allow',
        state: 'protection_inspection_boss_verify',
        message: 'protection_inspection_boss_verify_msg',
        url: 'tsr8Sign/protection_inspection_boss',
        filter: 'inspection_boss',
        filter2: 'value',
        system: true,
        firstName: 'protection_inspection_boss_verify_firstName',
        lastName: 'protection_inspection_boss_verify_lastName',
        hold: 'protection_supervisor_verify',
        not_dispatch: true
      }
    ],
    tsr8_4: [
      {
        name: 'کارشناس',
        value: 'welding_author',
        select: 'welding_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'welding_author_verify_allow',
        state: 'welding_author_verify',
        message: 'welding_author_verify_msg',
        url: 'tsr8Sign/welding_author',
        firstName: 'welding_author_verify_firstName',
        lastName: 'welding_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'سرپرست گروه',
        value: 'welding_supervisor_verify',
        select: 'welding_supervisor_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'welding_supervisor_verify_allow',
        state: 'welding_supervisor_verify',
        message: 'welding_supervisor_verify_msg',
        url: 'tsr8Sign/welding_supervisor',
        filter: 'بازرسی فنی',
        filter2: 'user_unit',
        firstName: 'welding_supervisor_firstName',
        lastName: 'welding_supervisor_lastName',
        hold: 'welding_author_verify'
      },
      {
        name: 'رئیس اداره بازرسی',
        value: 'welding_inspection_boss_verify',
        select: 'welding_inspection_boss_verify_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'welding_inspection_boss_verify_allow',
        state: 'welding_inspection_boss_verify',
        message: 'welding_inspection_boss_verify_msg',
        url: 'tsr8Sign/welding_inspection_boss',
        filter: 'inspection_boss',
        filter2: 'value',
        system: true,
        firstName: 'welding_inspection_boss_verify_firstName',
        lastName: 'welding_inspection_boss_verify_lastName',
        hold: 'welding_supervisor_verify',
        not_dispatch: true
      }
    ],
    tsr9_1: [
      {
        name: 'مسئول اجرا',
        value: 'fixed_mechanical_author',
        select: 'fixed_mechanical_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fixed_mechanical_author_verify_allow',
        state: 'fixed_mechanical_author_verify',
        message: 'fixed_mechanical_author_verify_msg',
        url: 'tsr9Sign/fixed_mechanical_author',
        firstName: 'fixed_mechanical_author_verify_firstName',
        lastName: 'fixed_mechanical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'fixed_mechanical_unit_boss',
        select: 'fixed_mechanical_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fixed_mechanical_unit_boss_verify_allow',
        state: 'fixed_mechanical_unit_boss_verify',
        message: 'fixed_mechanical_unit_boss_verify_msg',
        url: 'tsr9Sign/fixed_mechanical_unit_boss',
        firstName: 'fixed_mechanical_unit_boss_verify_firstName',
        lastName: 'fixed_mechanical_unit_boss_verify_lastName',
        filter: 'fixed_mechanical_boss',
        filter2: 'value',
        system: true,
        hold: 'fixed_mechanical_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'fixed_mechanical_planning_boss',
        select: 'fixed_mechanical_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fixed_mechanical_planning_unit_boss_verify_allow',
        state: 'fixed_mechanical_planning_boss_verify',
        message: 'fixed_mechanical_planning_boss_verify_msg',
        url: 'tsr9Sign/fixed_mechanical_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'fixed_mechanical_planning_unit_boss_verify_firstName',
        lastName: 'fixed_mechanical_planning_unit_boss_verify_lastName',
        hold: 'fixed_mechanical_unit_boss_verify'
      }
    ],
    tsr9_2: [
      {
        name: 'مسئول اجرا',
        value: 'rotating_mechanical_author',
        select: 'rotating_mechanical_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'rotating_mechanical_author_verify_allow',
        state: 'rotating_mechanical_author_verify',
        message: 'rotating_mechanical_author_verify_msg',
        url: 'tsr9Sign/rotating_mechanical_author',
        firstName: 'rotating_mechanical_author_verify_firstName',
        lastName: 'rotating_mechanical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'rotating_mechanical_unit_boss',
        select: 'rotating_mechanical_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'rotating_mechanical_unit_boss_verify_allow',
        state: 'rotating_mechanical_unit_boss_verify',
        message: 'rotating_mechanical_unit_boss_verify_msg',
        url: 'tsr9Sign/rotating_mechanical_unit_boss',
        filter: 'rotating_mechanical_boss',
        filter2: 'value',
        system: true,
        firstName: 'rotating_mechanical_unit_boss_verify_firstName',
        lastName: 'rotating_mechanical_unit_boss_verify_lastName',
        hold: 'rotating_mechanical_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'rotating_mechanical_planning_boss',
        select: 'rotating_mechanical_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'rotating_mechanical_planning_unit_boss_verify_allow',
        state: 'rotating_mechanical_planning_boss_verify',
        message: 'rotating_mechanical_planning_boss_verify_msg',
        url: 'tsr9Sign/rotating_mechanical_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'rotating_mechanical_planning_unit_boss_verify_firstName',
        lastName: 'rotating_mechanical_planning_unit_boss_verify_lastName',
        hold: 'rotating_mechanical_unit_boss_verify'
      }
    ],
    tsr9_3: [
      {
        name: 'مسئول اجرا',
        value: 'electrical_author',
        select: 'electrical_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_author_verify_allow',
        state: 'electrical_author_verify',
        message: 'electrical_author_verify_msg',
        url: 'tsr9Sign/electrical_author',
        firstName: 'electrical_author_verify_firstName',
        lastName: 'electrical_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'electrical_boss',
        select: 'electrical_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_unit_boss_verify_allow',
        state: 'electrical_unit_boss_verify',
        message: 'electrical_unit_boss_verify_msg',
        url: 'tsr9Sign/electrical_unit_boss',
        filter: 'electrical_boss',
        filter2: 'value',
        system: true,
        firstName: 'electrical_unit_boss_verify_firstName',
        lastName: 'electrical_unit_boss_verify_lastName',
        hold: 'electrical_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'electrical_planning_boss',
        select: 'electrical_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'electrical_planning_unit_boss_verify_allow',
        state: 'electrical_planning_boss_verify',
        message: 'electrical_planning_boss_verify_msg',
        url: 'tsr9Sign/electrical_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'electrical_planning_unit_boss_verify_firstName',
        lastName: 'electrical_planning_unit_boss_verify_lastName',
        hold: 'electrical_unit_boss_verify'
      }
    ],
    tsr9_4: [
      {
        name: 'مسئول اجرا',
        value: 'instrument_author',
        select: 'instrument_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'instrument_author_verify_allow',
        state: 'instrument_author_verify',
        message: 'instrument_author_verify_msg',
        url: 'tsr9Sign/instrument_author',
        firstName: 'instrument_author_verify_firstName',
        lastName: 'instrument_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'instrument_unit_boss_verify',
        select: 'instrument_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'instrument_unit_boss_verify_allow',
        state: 'instrument_unit_boss_verify',
        message: 'instrument_unit_boss_verify_msg',
        url: 'tsr9Sign/instrument_unit_boss',
        filter: 'instrument_boss',
        filter2: 'value',
        system: true,
        firstName: 'instrument_unit_boss_verify_firstName',
        lastName: 'instrument_unit_boss_verify_lastName',
        hold: 'instrument_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'instrument_planning_boss',
        select: 'instrument_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'instrument_planning_unit_boss_verify_allow',
        state: 'instrument_planning_boss_verify',
        message: 'instrument_planning_boss_verify_msg',
        url: 'tsr9Sign/instrument_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'instrument_planning_unit_boss_verify_firstName',
        lastName: 'instrument_planning_unit_boss_verify_lastName',
        hold: 'instrument_unit_boss_verify'
      }
    ],
    tsr9_5: [
      {
        name: 'مسئول اجرا',
        value: 'sensitive_equipment_author',
        select: 'sensitive_equipment_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'sensitive_equipment_author_verify_allow',
        state: 'sensitive_equipment_author_verify',
        message: 'sensitive_equipment_author_verify_msg',
        url: 'tsr9Sign/sensitive_equipment_author',
        firstName: 'sensitive_equipment_author_verify_firstName',
        lastName: 'sensitive_equipment_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'sensitive_equipment_boss',
        select: 'sensitive_equipment_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'sensitive_equipment_unit_boss_verify_allow',
        state: 'sensitive_equipment_unit_boss_verify',
        message: 'sensitive_equipment_unit_boss_verify_msg',
        url: 'tsr9Sign/sensitive_equipment_unit_boss',
        filter: 'sensitive_equipment_boss',
        filter2: 'value',
        system: true,
        firstName: 'sensitive_equipment_unit_boss_verify_firstName',
        lastName: 'sensitive_equipment_unit_boss_verify_lastName',
        hold: 'sensitive_equipment_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'sensitive_equipment_planning_boss',
        select: 'sensitive_equipment_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'sensitive_equipment_planning_unit_boss_verify_allow',
        state: 'sensitive_equipment_planning_boss_verify',
        message: 'sensitive_equipment_planning_boss_verify_msg',
        url: 'tsr9Sign/sensitive_equipment_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'sensitive_equipment_planning_unit_boss_verify_firstName',
        lastName: 'sensitive_equipment_planning_unit_boss_verify_lastName',
        hold: 'sensitive_equipment_unit_boss_verify'
      }
    ],
    tsr9_6: [
      {
        name: 'مسئول اجرا',
        value: 'repair_services_author',
        select: 'repair_services_author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'repair_services_author_verify_allow',
        state: 'repair_services_author_verify',
        message: 'repair_services_author_verify_msg',
        url: 'tsr9Sign/repair_services_author',
        firstName: 'repair_services_author_verify_firstName',
        lastName: 'repair_services_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'repair_services_boss',
        select: 'repair_services_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'repair_services_unit_boss_verify_allow',
        state: 'repair_services_unit_boss_verify',
        message: 'repair_services_unit_boss_verify_msg',
        url: 'tsr9Sign/repair_services_unit_boss',
        filter: 'repair_services_boss',
        filter2: 'value',
        system: true,
        firstName: 'repair_services_unit_boss_verify_firstName',
        lastName: 'repair_services_unit_boss_verify_lastName',
        hold: 'repair_services_author_verify',
        not_dispatch: true
      },
      {
        name: 'رئیس برنامه ریزی',
        value: 'repair_services_planning_boss',
        select: 'repair_services_planning_unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'repair_services_planning_unit_boss_verify_allow',
        state: 'repair_services_planning_boss_verify',
        message: 'repair_services_planning_boss_verify_msg',
        url: 'tsr9Sign/repair_services_planning_boss',
        filter: 'planning_boss',
        filter2: 'value',
        system: true,
        firstName: 'repair_services_planning_unit_boss_verify_firstName',
        lastName: 'repair_services_planning_unit_boss_verify_lastName',
        hold: 'repair_services_unit_boss_verify'
      }
    ],
    tsr10_1: [
      {
        name: 'بررسی کننده',
        value: 'repair_author',
        select: 'repair_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'repair_author_verify_allow',
        state: 'repair_author_verify',
        message: 'repair_author_verify_msg',
        url: 'tsr10Sign/repair_author',
        firstName: 'repair_author_verify_firstName',
        lastName: 'repair_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس تعمیرات',
        value: 'repair_boss',
        select: 'repair_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'repair_boss_verify_allow',
        state: 'repair_boss_verify',
        message: 'repair_boss_verify_msg',
        url: 'tsr10Sign/repair_boss',
        filter: 'repair_boss',
        filter2: 'value',
        system: true,
        firstName: 'repair_boss_verify_firstName',
        lastName: 'repair_boss_verify_lastName',
        hold: 'repair_boss_author_verify',
        hold: 'repair_author_verify',
        not_dispatch: true,
        filter3: 'repair_supervisor_id',
      }
    ],
    tsr10_2: [
      {
        name: 'بررسی کننده',
        value: 'operation_author',
        select: 'operation_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'operation_author_verify_allow',
        state: 'operation_author_verify',
        message: 'operation_author_verify_msg',
        url: 'tsr10Sign/operation_author',
        firstName: 'operation_author_verify_firstName',
        lastName: 'operation_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس بهره‌برداری',
        value: 'operation_boss',
        select: 'operation_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'operation_boss_verify_allow',
        state: 'operation_boss_verify',
        message: 'operation_boss_verify_msg',
        url: 'tsr10Sign/operation_boss',
        filter: 'operation_boss',
        filter2: 'value',
        system: true,
        firstName: 'operation_boss_verify_firstName',
        lastName: 'operation_boss_verify_lastName',
        hold: 'operation_author_verify',
        not_dispatch: true,
        filter3: 'operation_supervisor_id',
      }
    ],
    tsr10_3: [
      {
        name: 'بررسی کننده',
        value: 'fire_author',
        select: 'fire_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fire_author_verify_allow',
        state: 'fire_author_verify',
        message: 'fire_author_verify_msg',
        url: 'tsr10Sign/fire_author',
        firstName: 'fire_author_verify_firstName',
        lastName: 'fire_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس ایمنی و آتش نشانی',
        value: 'fire_boss',
        select: 'fire_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'fire_boss_verify_allow',
        state: 'fire_boss_verify',
        message: 'fire_boss_verify_msg',
        url: 'tsr10Sign/fire_boss',
        filter: 'fire_boss',
        filter2: 'value',
        system: true,
        firstName: 'fire_boss_verify_firstName',
        lastName: 'fire_boss_verify_lastName',
        hold: 'fire_author_verify',
        not_dispatch: true,
        filter3: 'fire_supervisor_id',
      }
    ],
    tsr10_4: [
      {
        name: 'بررسی کننده',
        value: 'process_author',
        select: 'process_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'process_author_verify_allow',
        state: 'process_author_verify',
        message: 'process_author_verify_msg',
        url: 'tsr10Sign/process_author',
        firstName: 'process_author_verify_firstName',
        lastName: 'process_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس مهندسی فرآیند',
        value: 'process_boss',
        select: 'process_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'process_boss_verify_allow',
        state: 'process_boss_verify',
        message: 'process_boss_verify_msg',
        url: 'tsr10Sign/process_boss',
        filter: 'process_boss',
        filter2: 'value',
        system: true,
        firstName: 'process_boss_verify_firstName',
        lastName: 'process_boss_verify_lastName',
        not_dispatch: true,
        filter3: 'process_supervisor_id',
      }
    ],
    tsr10_5: [
      {
        name: 'بررسی کننده',
        value: 'inspection_author',
        select: 'inspection_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'inspection_author_verify_allow',
        state: 'inspection_author_verify',
        message: 'inspection_author_verify_msg',
        url: 'tsr10Sign/inspection_author',
        firstName: 'inspection_author_verify_firstName',
        lastName: 'inspection_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس بازرسی فنی',
        value: 'inspection_boss',
        select: 'inspection_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'inspection_boss_verify_allow',
        state: 'inspection_boss_verify',
        message: 'inspection_boss_verify_msg',
        url: 'tsr10Sign/inspection_boss',
        filter: 'inspection_boss',
        filter2: 'value',
        system: true,
        firstName: 'inspection_boss_verify_firstName',
        lastName: 'inspection_boss_verify_lastName',
        not_dispatch: true,
        filter3: 'inspection_supervisor_id',
      }
    ],
    tsr10_6: [
      {
        name: 'بررسی کننده',
        value: 'general_author',
        select: 'general_author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_author_verify_allow',
        state: 'general_author_verify',
        message: 'general_author_verify_msg',
        url: 'tsr10Sign/general_author',
        firstName: 'general_author_verify_firstName',
        lastName: 'general_author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss',
        select: 'general_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_verify_allow',
        state: 'general_boss_verify',
        message: 'general_boss_verify_msg',
        url: 'tsr10Sign/general_boss',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName',
        not_dispatch: true,
        filter3: 'general_supervisor_id',
      }
    ],
    tsr11: [
      {
        name: 'مسئول TSR',
        value: 'author',
        select: 'author_select',
        // itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'author_verify_allow',
        state: 'author_verify',
        message: 'author_verify_msg',
        url: 'tsr10Sign/author',
        firstName: 'author_firstName',
        lastName: 'author_lastName',
        notShowDefault: true,
        cantReject: true,
        not_have_check: true
      },
      {
        name: 'سرپرست گروه',
        value: 'supervisor',
        select: 'supervisor_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'supervisor_verify_allow',
        state: 'supervisor_verify',
        message: 'supervisor_verify_msg',
        url: 'tsr11Sign/supervisor',
        filter: 'خدمات فنی_SD_مهندسی فرآیند و کنترل تولید_SD_بازرسی فنی_SD_آزمایشگاه_SD_مهندسی عمومی و پروژه ها',
        filter2: 'user_unit',
        firstName: 'supervisor_verify_firstName',
        lastName: 'supervisor_verify_lastName'
      },
      {
        name: 'رئیس مهندسی عمومی',
        value: 'general_boss',
        select: 'general_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'general_boss_verify_allow',
        state: 'general_boss_verify',
        message: 'general_boss_verify_msg',
        url: 'tsr11Sign/general_boss',
        filter: 'general_boss',
        filter2: 'value',
        system: true,
        firstName: 'general_boss_verify_firstName',
        lastName: 'general_boss_verify_lastName'
      }
    ],
    tsr12: [
      {
        name: 'بررسی کننده',
        value: 'author',
        select: 'author_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'author_verify_allow',
        state: 'author_verify',
        message: 'author_verify_msg',
        url: 'tsr12Sign/author',
        // filter2: 'value',
        // filter: 'author',
        // system: true,
        firstName: 'author_verify_firstName',
        lastName: 'author_verify_lastName',
        notShowDefault: true,
        cantReject: true
      },
      {
        name: 'رئیس واحد',
        value: 'unit_boss',
        select: 'unit_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'unit_boss_verify_allow',
        state: 'unit_boss_verify',
        message: 'unit_boss_verify_msg',
        url: 'tsr12Sign/unit_boss',
        filter: 'unit_boss',
        filter2: 'value',
        system: true,
        firstName: 'unit_boss_verify_firstName',
        lastName: 'unit_boss_verify_lastName'
      },
      {
        name: 'رئیس اداره/امور',
        value: 'office_boss',
        select: 'office_boss_select',
        itemReject: [{ name: 'اصلاحیه', value: 'comment' }],
        permission: 'office_boss_verify_allow',
        state: 'office_boss_verify',
        message: 'office_boss_verify_msg',
        url: 'tsr12Sign/office_boss',
        filter: 'office_boss',
        filter2: 'value',
        system: true,
        firstName: 'office_boss_verify_firstName',
        lastName: 'office_boss_verify_lastName',
        not_dispatch: true
      }
    ]
  }
}
export default ListSign
